{
    var x : integer
    integer func calculateArea = {
        var length : integer
        var width : integer;
        length := 5
        width := 3
        put "Length: ", length, ", Width: ", width;
        length * width
    }
    ;
    put "Calculating area using calculateArea function: ", calculateArea
    if calculateArea = 15 then
        put "-- Success: Area = 15 --"
    else
        put "-- Failure: Area != 15 --"
    end if
}