{
  % Program 3: Conditional statements dan boolean operations
  var a : integer
  var b : integer
  var isEqual : boolean
  var isGreater : boolean;

  get a, b

  isEqual := a = b
  isGreater := a > b

  if isEqual then
     put "Kedua bilangan sama"
  else
     if isGreater then
        put "Bilangan pertama lebih besar"
     else
        put "Bilangan kedua lebih besar"
     end if
  end if

  put "a = ", a, ", b = ", b
}