{
    integer func funcNoParam = 42
    integer func funcWithParam(x : integer,y : integer) = x+y + 10

    proc procNoParam
    {
        ;
        put "Proc No Param Called", skip
    }

    proc procWithParam(x : integer,y : integer)
    {
        ;
        put "Proc With Param: ", x+y, skip
    }
    ;

    procNoParam
    procWithParam(100,100)
    
    put "Func No Param: ", funcNoParam, skip
    put "Func With Param: ", funcWithParam(100,100), skip
}
